version: '3.8'
services:
  db:
    image: sleonard9704/trio-task-db
    build: ./db
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flask-db
  flask-app:
    build: ./flask-app
    container_name: flask-app
    image: sleonard9704/trio-task-flask-app
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf